version: "3.9"
services:
  transreader-client:
    build:
      context: ./client
    ports:
      - 3000:3000
    env_file:
      - "./client/.env.local"
    image: znicoll/transreader-client
  transreader-server:
    build:
      context: ./server
    ports:
      - 5000:5000
    env_file:
      - "./server/.env.local"
    volumes:
      - ${HOME}/.config/gcloud:/root/.config/gcloud
    image: znicoll/transreader-server
